# Generated by Django 4.2.3 on 2023-08-02 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litreview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='followed_user', through='litreview.UserFollows', to=settings.AUTH_USER_MODEL, verbose_name='Abonnements'),
        ),
    ]
